name: On_Push_Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  make_static_files:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # check what files are present in root folder
    - name: Check root folder
      run: ls -la

    # cd to ./redwoodap folder before running yarn
    - name: cd to ./redwoodap folder
      run: cd redwoodap
    # Install rw dependencies via yarn with commands yarn install and yarn rw build
    - name: Install rw dependencies and build static files
      run: yarn install && yarn rw build

    - name: Setup Environment
      uses: actions/setup-node@v3
      with:
        node-version: 18.1.0 #check if this needs to be updated from time to time
    - run: npm install #check what commands need to be executed before static files can be generated
      
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
    - name: change latest tag
      uses: EndBug/latest-tag@latest
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       token: ${{ secrets.GITHUB_TOKEN }}
      with:
        # You can change the name of the tag or branch with this input.
        # Default: 'latest'
        ref: 'latest'
        # If a description is provided, the action will use it to create an annotated tag. If none is given, the action will create a lightweight tag.
        # Default: ''
        description: 'latest version of the frontend dmbon-assistant' 
        # Force-update a branch instead of using a tag.
        # Default: false
        force-branch: true
    
  #job that will take all the files from ./redwoodap/web/dist and pushes them to other repo (dmbon-assistant) in the main branch in folder ./frontend
  push_static_files:
    runs-on: ubuntu-latest
    needs: make_static_files
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main #vliz-be-opsci/dmbon-assistant@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'redwoodap/web/dist' #redwoodap/web/dist
          destination-github-username: 'vliz-be-opsci' #vliz-be-opsci/dmbon-assistant@main
          destination-repository-name: 'dmbon-assistant'
          target-branch: main
          target-folder: frontend
          
  release-manager:
    needs: make_static_files 
    name: Check if ready for release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: echo ${{ github.event.repository.name }}
        name: Get latest tag of repo 
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: vliz-be-opsci/${{ github.event.repository.name }}  # The repository to scan. Change the part before the / to name or organisation where repo resides
          releases-only: false  # Set to true if you want to know the tag linked to the latest release
        id: vliz-be-opsci  # The step ID to refer to later.

      - run: echo "${{ github.event.repository.name }} is at version ${{ steps.vliz-be-opsci.outputs.tag }}"
        name: check if latest tag meets maor release requirements
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ steps.vliz-be-opsci.outputs.tag }}
          regex: 'v[0-9].0.0'
      - name: Create release
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: major
